version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    container_name: payment-system-app-container
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "${APP_PORT}:${APP_PORT}"
  postgres:
    image: postgres:15.3
    container_name: payment-system-postgres-container
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/db/scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
  redis:
    image: redis/redis-stack-server:latest
    container_name: payment-system-redis-container
    restart: always
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

volumes:
  db:
    driver: local
